Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AsciiComments:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
