version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
  web:
    build: .
    command: sleep infinity
    volumes:
      - .:/app
      - gem_vol:/usr/local/bundle
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - selenium_chrome
      - smtp
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db_vol:
  gem_vol:
